name: Update Lista IPTV

on:
  schedule:
    - cron: '0 0,12 * * *' # Ruleaza automat la ora 00:00 si 12:00 (zilnic)
  workflow_dispatch: # Iti permite sa pornesti manual actualizarea oricand

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permisiune pentru a scrie fisierul in repo-ul tau

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Descarcare si curatare lista
        run: |
          # Folosim curl cu timeout si sed pentru inlocuire instantanee in memorie
          curl -s -L "https://wlog.ro/api/iptv.m3u" | sed 's/ | Wlog.Ro//g' > iptv_curat.m3u

      - name: Salvare modificari pe GitHub
        run: |
          git config --global user.name "IPTV-Bot"
          git config --global user.email "bot@github.com"
          git add iptv_curat.m3u
          # Commit-ul se face doar daca s-a schimbat ceva in lista
          git commit -m "Lista actualizata: $(date +'%d-%m-%Y %H:%M')" || exit 0
          git push
